<?
$CgiUser="nagiosadmin";
$StatusCgi="/usr/local/nagios/sbin/status.cgi";
$Language="english";
$Base="/usr/local/nagios/share/nagvis";
$HTMLBase="http://".$_SERVER['HTTP_HOST']."/nagios/nagvis";
$CgiPath="/usr/local/nagios/sbin/";
$ConfigPath="/usr/local/nagios/etc/";
$RefreshTime="30";
$cfgPath=$Base."/etc/";
$cfgFolder=$Base."/etc/maps/";
$mapFolder=$Base."/maps/";
$iconBaseFolder=$Base."/iconsets/";
$iconHTMLBaseFolder=$HTMLBase."/iconsets/";
$indexInc="index.nagvis.inc";
$defaultIcons="std_medium";
$RotateMaps="0";
$maps=array("demo");
$Header="1";
$headerCount="3";
$check_config="0";
$Autoupdate_frequency="5";
$headerInc="header.nagvis.inc";
$version="0.9a5+";
$title="NagVis - CVS MAIN ".$version;
?>
