<?
$CgiUser="nagiosadmin";
$Language="english";
$Base="/usr/local/nagios/share/nagvis";
$HTMLBase="/nagios/nagvis";
$CgiPath="/usr/local/nagios/sbin/";
$HTMLCgiPath="/nagios/cgi-bin";
$RefreshTime="90";
$cfgPath=$Base."/etc/";
$cfgFolder=$Base."/etc/maps/";
$mapFolder=$Base."/maps/";
$iconBaseFolder=$Base."/iconsets/";
$iconHTMLBaseFolder=$HTMLBase."/iconsets/";
$indexInc="index.nagvis.inc";
$defaultIcons="std_medium";
$RotateMaps="0";
$maps=array("demo");
$Header="1";
$headerCount="3";
$check_config="0";
$Autoupdate_frequency="25";
$headerInc="header.nagvis.inc";
$version="0.9b1";
$title="NagVis ".$version;
?>
