##########################################################################
##     	                           NagVis                              ##
##                                                                      ##
##               *** Config-Datei für das Header-Menu ***               ##
##                                                                      ##
##      Autor von NagVis 0.0.3: Jörg Linge <pichfork@ederdrom.de>       ##
##                                                                      ##
##         Umgschrieben von Perl in PHP und weiterentwickelt by         ##
##                      Michael Lübben(MiCkEy2002)                      ##
##                                                                      ##
##                               Lizenz GPL                             ##
##########################################################################

# Text;URL
Netzwerkplan;index.php?map=1
Nagios-Cluster;index.php?map=2
Nagios-Tests;index.php?map=4
Config WUI;config.php?map=1
Config WUI;config.php?map=2
Config WUI;config.php?map=4
