##########################################################################
##     	                           NagVis                              ##
##                                                                      ##
##               *** Config-Datei für das Header-Menu ***               ##
##                                                                      ##
##      Autor von NagVis 0.0.3: Jörg Linge <pichfork@ederdrom.de>       ##
##                                                                      ##
##         Umgschrieben von Perl in PHP und weiterentwickelt by         ##
##                      Michael Lübben(MiCkEy2002)                      ##
##                                                                      ##
##                               Lizenz GPL                             ##
##########################################################################

# Text;MAP
Server;index.php?map=demo
ConfigWUI;config.php
